### ISSUE TITLE
How to get coordinates from output file?

### ISSUE THREAD

**Issue by tarak77** [nerettilab/SIMBA3D#1]
Hello,
I was trying out SIMBA3D on my data by following the steps mentioned to do so. What I noticed is that the output file in .npz format has a single key "summary". Is it possible to get the coordinates of the output structure as an array using a key, say, the "X_evol" key?
Also I could be wrong but the simba3d-print function didn't help me to do that.
I could go around that problem by converting from .npz to .mat and then finding the coordinates, but is there a way to do in python?

Any help will be appreciated.

**Comment by michael-m-rosenthal** [comment]
Yes,

X_evol is the key you want. It either contains a single curve or an
collection of iteratively evolving curves (if you ask it to store the
iterations which is mostly for debugging and making cool looking graphics).

The other trick to importing it into python is to use the item() command. I
am not sure exactly why, but for some reason python numpy loading of
dictionaries are not automatically loaded as an object one might
intuitively expect. That is probably not a correct explanation, but in
short you need to use the item function like seen below or you get a
Traceback error for some reason.

import numpy as np
data = np.load('resultdatafile.npz')['summary'].item()
X_evol=data['X_evol']
curve=X_evol[0] # 3d curve stored in index 0

Also, the print command should create text that can be copied and pasted
directly into a python script or terminal.

Best
Michael M. Rosenthal

On Jun 25, 2018 3:08 PM, "Tarak Shisode" <notifications@github.com> wrote:

Hello,
I was trying out SIMBA3D on my data by following the steps mentioned to do
so. What I noticed is that the output file in .npz format has a single key
"summary". Is it possible to get the coordinates of the output structure as
an array using a key, say, the "X_evol" key?
Also I could be wrong but the simba3d-print function didn't help me to do
that.
I could go around that problem by converting from .npz to .mat and then
finding the coordinates, but is there a way to do in python?

Any help will be appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/1>, or mute the thread

**Comment by tarak77** [comment]
Thanks!

**Comment by michael-m-rosenthal** [comment]
I will make a note to add an example script in the tutorial for loading the npz result into python.
