### ISSUE TITLE
Setting Initial curve and working genome wide ?

### ISSUE THREAD

**Issue by tarak77** [nerettilab/SIMBA3D#4]
Hi Michael,

I am able to produce results setting the initial curve to zero and using a single chromosome contact matrix. 
How to set the initial curve in order to obtain an ensemble of chromosomal structures, interestingly is it possible to obtain an ensemble of structures of entire genome for a particular cell?

Any help will be great!

Thanks,
Tarak

**Comment by michael-m-rosenthal** [comment]
Hi Tarak,

(1) The first part on how to initialize the curve to obtain an ensemble is addressed below:

There are a variety of ways to accomplish it. One way is to randomly generate a list of initialized curves and then create a list of tasks that will loop through each initialization. This gives you the most control over the process since you can initialize from whatever distribution you wish and easily repeat the experiment later using different tuning parameters if needed.

Another option is to not provide an initialization and include
`'randomize_initialization': true,`
within the json task. This will tell SIMBA3D to randomly initialize the curve. It will use Guassian random noise to initialize the curve. The initialized curve generated should be stored in the output result.

(2) For the second part, Is it possible to obtain an ensemble of structures of entire genome? 

Yes, however depending on the resolution, you may run out of physical memory. We have done this in a paper for each chormosome of the full chromosome separately in the following paper.
https://www.biorxiv.org/content/early/2018/05/07/316265

You should be able to estimate a full chromosome matrix structure using a multi-scale approach. It just occurred to me that an example of the multi-scale setup script has not been posted yet. I will post it soon.

**Comment by tarak77** [comment]
Ok. I could be wrong but what I understood from (2) is that whole genome structures are possible at large bin sizes provided we supply a input contact matrix containing all 20 chromosomal pairs? 

I am eagerly waiting for the multi-scale approach setup script for the same.

I had a favor to ask, will it be possible to help/provide the example scripts used in simulating the double spiral curve and the corresponding contact matrix(Supplementary figure S1, A and B). I really appreciate your help!

Thanks.

**Comment by michael-m-rosenthal** [comment]
It should not be a problem supplying the simulated data case.

I am cleaning up the setup script for the multiscale tasklist now and
adding documentation for it.

On Aug 14, 2018 1:55 PM, "Tarak Shisode" <notifications@github.com> wrote:

Ok. I could be wrong but what I understood from (2) is that whole genome
structures are possible at large bin sizes provided we supply a input
contact matrix containing all 20 chromosomal pairs?

I am eagerly waiting for the multi-scale approach setup script for the same.

I had a favor to ask, will it be possible to help/provide the example
scripts used in simulating the double spiral curve and the corresponding
contact matrix(Supplementary figure S1, A and B). I really appreciate your
help!

Thanks.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/4#issuecomment-412979057>,
or mute
the thread

**Comment by tarak77** [comment]
Great! Please let me know when done updating.

**Comment by michael-m-rosenthal** [comment]
I have added a multiscale example for one cell and chromosome.

I have a few more examples to add, but this should get you started

**Comment by tarak77** [comment]
Thanks, also is it possible to provide the scripts used to generate the simulated double spiral curve and the corresponding contact matrix?

**Comment by michael-m-rosenthal** [comment]
Yes, it will take a little time to document it.

**Comment by michael-m-rosenthal** [comment]
the simulated_spiral_data_example has been added to the examples directory

**Comment by tarak77** [comment]
Awesome! thanks.
