### ISSUE TITLE
Getting whole genome models?

### ISSUE THREAD

**Issue by tarak77** [nerettilab/SIMBA3D#6]
Hi Michael,

It has become more important now to work on the whole genome haploid/diploid cell models rather than individual chromosomes. Is it possible to use SIMBA3D to generate such haploid/diploid cell whole genome models? If yes, will it be possible to provide an example?

Thanks again!

**Comment by michael-m-rosenthal** [comment]
Hi,

We have begun working on doing full reconstruction at finer resolutions.

Currently there is a limitation in the amount of memory a system has to
load the data. We are looking into streaming data from file and using
sparse matrix python objects.

At this point, SIMBA3D should be able to estimate lower resolutions for a
general aritecture and then estimate higher order structures locally. The
higher order structures can be aligned to overall aritecture.

We are exploring several options.




On Sep 9, 2018 5:43 PM, "Tarak Shisode" <notifications@github.com> wrote:

Hi Michael,

It has become more important now to work on the whole genome
haploid/diploid cell models rather than individual chromosomes. Is it
possible to use SIMBA3D to generate such haploid/diploid cell whole genome
models? If yes, will it be possible to provide an example?

Thanks again!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/6>, or mute the thread

**Comment by tarak77** [comment]
Ok, thanks!
