### ISSUE TITLE
Regarding BFGS

### ISSUE THREAD

**Issue by tarak77** [nerettilab/SIMBA3D#8]
Hi @michael-m-rosenthal ,

I hope you are doing good. Recently I was trying to run simba3d to find the chromosome structure at high resolution, say 100kb. I noticed that the energy did not converge but seem to diverge for such resolutions(it started increasing in the negative direction and taking many hours to complete). Is there any reason for that?

Thanks for your help.

**Comment by michael-m-rosenthal** [comment]
The settings of the penalty terms by default use only the data term. If
your data is sparse the solution might not be well defined. Consider
adjusting the smoothing penalties slightly. There are two coded in which
correspond to the bioarxive paper.

On Oct 17, 2018 12:24 PM, "Tarak Shisode" <notifications@github.com> wrote:

Hi @michael-m-rosenthal <https://github.com/michael-m-rosenthal> ,

I hope you are doing good. Recently I was trying to run simba3d to find the
chromosome structure at high resolution, say 100kb. I noticed that the
iterations did not converge but seem to diverge for such resolutions. Is
there any reason for that?

Thanks for your help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/8>, or mute the thread

**Comment by tarak77** [comment]
Okay, thanks
